API 7558 PractitionerRole Datamart Model
department-of-veterans-affairs/health-apis-datamart-synthetic-records pull request #150
Opened 2021-06-03 19:55 UTC by that-guy-is-it

2021-06-03 20:36 UTC, that-guy-is-it commented
@nmoisan  @jtaylor-va  @haidong I realize I forgot to add a ping on the description, so I am adding it here as a comment.

2021-06-04 11:34 UTC, nmoisan approved these changes
LGTM

2021-06-04 13:00 UTC, bschofield-va submitted a review, later dismissed

2021-06-04 13:08 UTC, haidong approved these changes

2021-06-04 18:13 UTC, jblefkove-va commented on db/migration/V17_0__create_practitioner_role.sql
> +  [PractitionerRole] [varchar](MAX),
should this also be `not null`?

2021-06-04 18:15 UTC, jblefkove-va commented on db/migration/V17_0__create_practitioner_role.sql
> +  [Specialty] [varchar](100) null,
@nmoisan any concerns about 100 characters supporting multiple specialties?

2021-06-04 18:16 UTC, jblefkove-va commented on db/migration/V17_0__create_practitioner_role.sql
> +  [Sta3n] [smallint] not null,
Do we need `sta3n` column? I don't think we search on this one.

2021-06-07 13:42 UTC, nmoisan commented on db/migration/V17_0__create_practitioner_role.sql
> +  [Sta3n] [smallint] not null,
I doubt it, was just matching existing filters within `Practitioner` when i wrote up the schema last week.

2021-06-07 13:45 UTC, nmoisan commented on db/migration/V17_0__create_practitioner_role.sql
> +  [Specialty] [varchar](100) null,
The max value within the table is 22 characters. perhaps we can expand it to 255 here just to be on the safe side? (if we go the route of aggregating in the db).

2021-06-07 13:48 UTC, jblefkove-va commented on db/migration/V17_0__create_practitioner_role.sql
> +  [Specialty] [varchar](100) null,
I'm good with 255

2021-06-07 13:49 UTC, jblefkove-va commented on db/migration/V17_0__create_practitioner_role.sql
> +  [Sta3n] [smallint] not null,
Let's omit this column for now then

2021-06-07 13:49 UTC, jblefkove-va requested changes
see inline

2021-06-07 14:42 UTC, jblefkove-va approved these changes

2021-06-07 14:47 UTC, merged