API 7735 Table Populate Practitioner Role
department-of-veterans-affairs/health-apis-datamart-synthetic-records pull request #154
Opened 2021-06-10 15:34 UTC by that-guy-is-it

2021-06-10 16:22 UTC, nmoisan commented on datamart/dm-records-1017283180V801730/dmPraRole294582.json
> +    "role" : {
This *may* have to be expanded to allow an array. Will discuss in this afternoon's meeting.

2021-06-10 16:49 UTC, jblefkove-va commented
Shouldn't each practitioner role have a reference to its parent practitioner?

2021-06-10 16:57 UTC, nmoisan commented on datamart/dm-records-1017283180V801730/dmPraRole294582.json
> +    "role" : {
I am going to redact this. 1 role should be good. All my questions now are regarding period and if we can forego it and just put out active role/specialties.

2021-06-10 21:34 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/DatamartFilenamePatterns.java
> +    jsonFileRegex.put(DatamartPractitionerRole.class, "^dmPraRole.*json$");
This should be `PraRol` to keep with convention

2021-06-10 21:35 UTC, bschofield-va commented on datamart/dm-records-1017283180V801730/dmPraRole294582.json
> +{
These files are named incorrectly. They should 3 letter PascalCase words to represent the resources.
`PraRol`

2021-06-10 21:46 UTC, bschofield-va requested changes
fix file names to match 3 letter convention

2021-06-11 13:39 UTC, jblefkove-va commented on datamart/dm-records-1017283180V801730/dmPraRole294582.json
> +  "cdwId" : "294582:P",
@nmoisan to confirm `:P` is the designated suffix for `PractitionerRole` IDs?

2021-06-11 13:43 UTC, nmoisan commented on datamart/dm-records-1017283180V801730/dmPraRole294582.json
> +  "cdwId" : "294582:P",
yes that will be the suffix. I'm working up what I believe an actual solution will be for our aggregation problems. So `Role` will need to accept an array but that's the only change I see necessary here. I will be posted the API-facing schema in Slack shortly since that will also need to be adjusted a bit.

2021-06-15 13:47 UTC, that-guy-is-it commented
In order to address the changes to the Practitioner Role db schema, this PR will be closed and reopened at a later time, after a new migration is added and Data Query has been updated.

2021-06-15 13:47 UTC, closed without merging