API-8342: PractitionerRole Specialty Mapping
department-of-veterans-affairs/health-apis-datamart-synthetic-records pull request #162
Opened 2021-07-06 15:21 UTC by apeirats-va

1. fixes PK on `Practitioner`
2. Adds `PractitionerRole_Specialty_Map` entity, consistent with CDW schema
3. Updates minimart-maker to re-index specialty mappings for each PractitionerRole file.

2021-07-06 15:23 UTC, apeirats-va commented on db/migration/V17_4__alter_practitioner.sql
> +GO
This is a bug fix. The `Practitioner` resource was sometimes locking up due to the PK migration to a composite id. Minimart uses the `CompositeCdwId` as its primary key, while the db was still using the raw `cdwId` column.

2021-07-06 15:24 UTC, apeirats-va commented on db/migration/V17_5__create_practitioner_role_specialty_map.sql
> +GO
The `search by specialty` query will end up looking similar to this:
```
SELECT CDWIdNumber, CDWIdResourceCode, Active, PractitionerNPI, PractitionerFamilyName from dq.app.PractitionerRole src
where Active = 1
AND EXISTS(
	SELECT 1
	FROM dq.app.PractitionerRole_Specialty_Map map
	WHERE map.SpecialtyCode = 'V111000'
		AND map.PractitionerRoleIdNumber = src.CDWIdNumber
		AND map.PractitionerRoleResourceCode = src.CDWIdResourceCode
)
```

2021-07-07 17:44 UTC, bschofield-va requested changes
I want to hold this a smidge and make sure I understand the design choices being made here

2021-07-08 18:13 UTC, bschofield-va approved these changes

2021-07-09 12:56 UTC, bschofield-va approved these changes

2021-07-09 13:16 UTC, merged