API 11224 Observation lastUpdated Migration
department-of-veterans-affairs/health-apis-datamart-synthetic-records pull request #219
Opened 2021-11-23 21:16 UTC by that-guy-is-it

First PR for the multi-PR task, 11224. This PR was intentionally delayed in the hopes of getting the second PR (for DQ) ready also, but since it is taking longer than expected, I am opening this first PR alone for now.

2021-11-24 14:49 UTC, that-guy-is-it commented
@nmoisan @jtaylor-va @haidong I realized I forgot to ping! Apologies! This is a schema change so you guys need to double check too.

2021-11-24 14:51 UTC, nmoisan commented
LGTM, matches our naming convention and datatype. 👍

2021-11-24 17:27 UTC, ilaflamme-va commented on db/migration/V22_0__alter_observation.sql
> +ALTER TABLE [App].[Observation] ADD [LastUpdated] [DATE] NULL
Can this be `not null`? 
Is `LastUpdated` populated with the creation date when it is first loaded. Every subsequent change would alter this value.

2021-11-24 17:29 UTC, ilaflamme-va commented on db/migration/V22_0__alter_observation.sql
> +ALTER TABLE [App].[Observation] ADD [LastUpdated] [DATE] NULL
If this doesn't matter, it looks fine to me.

2021-11-24 17:29 UTC, nmoisan commented on db/migration/V22_0__alter_observation.sql
> +ALTER TABLE [App].[Observation] ADD [LastUpdated] [DATE] NULL
you are right actually! I missed that. This matches our design too. We define `LastUpdated` as non-nullable with a default upon first load.

2021-11-24 17:46 UTC, ilaflamme-va commented on db/migration/V22_0__alter_observation.sql
> +ALTER TABLE [App].[Observation] ADD [LastUpdated] [DATE] NULL
Thats what I thought :) Thanks for clarifying.

2021-11-24 17:50 UTC, ilaflamme-va requested changes
Make last updated not null.

2021-11-24 17:56 UTC, ilaflamme-va commented
A couple things need to happen:
- The ObservationEntity does not have a LastUpdated field, DQ will need an updated and the dependency updated
-  MitreMinimartMaker will need to populate the synthetic entities with a value upon loading of the db. see here: https://github.com/department-of-veterans-affairs/health-apis-datamart-synthetic-records/blob/ebb215eb4cf3a169ffca00181777c37d81c1d679/minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java#L113

2021-11-24 18:50 UTC, that-guy-is-it commented
Wouldn't merging this as `null` for the time being be beneficial, since the Observation Entity has to be updated and requires a built synthetic database? A second migration can set it to `not null` once it can be populated.

2021-11-24 18:52 UTC, ilaflamme-va commented
A follow-up PR is fine, if this null version is just place-holder as things get sorted out.

2021-11-24 18:54 UTC, that-guy-is-it commented
> A follow-up PR is fine, if this null version is just place-holder as things get sorted out.

It is, since a second PR is likely necessary for populating anyway.

2021-11-29 19:09 UTC, that-guy-is-it commented
Due to a necessity to add `lastUpdated` to the Datamart Payload separately, the populating of this column will be done in a future PR, as originally planned. For the time being, this migration will merge using a `NULL`, and after the DQ model is updated and the population is done, a second migration will set it to `NOT NULL`.

2021-11-29 19:18 UTC, jblefkove-va approved these changes
:shipit:

2021-11-29 19:19 UTC, ilaflamme-va approved these changes

2021-11-29 19:20 UTC, merged