API-11684 add Encounter table
department-of-veterans-affairs/health-apis-datamart-synthetic-records pull request #225
Opened 2021-12-02 20:24 UTC by taylorrassmannlibertyits

Add encounter table to synthetic records

2021-12-02 20:25 UTC, taylorrassmannlibertyits commented
CC: @nmoisan @jtaylor-va @haidong

2021-12-02 20:34 UTC, nmoisan reviewed
@jtaylor-va we have two extra fields in the view `StartDateTime` and `EndDateTime` - can you provide any clarity on those 2 fields and what they are for in the view?

2021-12-02 20:34 UTC, nmoisan commented on db/migration/V23_0__add_encounter.sql
> +    [CDWId] [varchar](26) NOT NULL,
composite cdwid. `bigint` and `char(1).

2021-12-02 20:34 UTC, nmoisan commented on db/migration/V23_0__add_encounter.sql
> +    [DateUTC] [smalldatetime] NULL,
`datetime2(0)` here

2021-12-02 20:34 UTC, nmoisan commented on db/migration/V23_0__add_encounter.sql
> +    [LastUpdated] [smalldatetime] DEFAULT getutcdate(),
`date` here

2021-12-02 20:37 UTC, jtaylor-va commented
`startDateTime` and `endDateTime` are searchable fields to be able to search by beginning of the `encounter` and end of the `encounter`. Both are `datetime2(0)`.

2021-12-02 21:01 UTC, taylorrassmannlibertyits commented
CC: @nmoisan @jtaylor-va @haidong I've removed indexing since we only have a small amount of synth records to add in a future PR.

I also am only using `DateUTC` and `EndDateTime`. Is this sufficient?

2021-12-02 21:04 UTC, jtaylor-va commented
I'm not a huge fan of that because `startDateTime` and `endDateTime` have meaning. Does the API rely on a view having a `DateUTC` column?

2021-12-02 21:06 UTC, taylorrassmannlibertyits commented
> I'm not a huge fan of that because `startDateTime` and `endDateTime` have meaning. Does the API rely on a view having a `DateUTC` column?

The API hasn't been implemented yet so we can have either one. I did `DateUTC` for synthetic records consistency. I am open to change for clarity :)

2021-12-03 14:34 UTC, jblefkove-va requested changes

2021-12-03 14:34 UTC, jblefkove-va commented on db/migration/V23_0__add_encounter.sql
> + * Create Encounter Table.
remove superfluous comment

2021-12-03 14:34 UTC, jblefkove-va commented on db/migration/V23_0__add_encounter.sql
> +    [CDWIdResourceCode] char(1) NULL,
Shouldn't the PK fields be `NOT NULL`?

2021-12-03 14:34 UTC, jblefkove-va commented on db/migration/V23_0__add_encounter.sql
> +    [LastUpdated] [date] DEFAULT getutcdate(),
`LastUpdated` can be `NOT NULL`. Also, since minimart-manager will handle the population of this field, let's not default it here.

2021-12-03 14:34 UTC, jblefkove-va commented on db/migration/V23_0__add_encounter.sql
> +    CONSTRAINT PK_Encounter PRIMARY KEY CLUSTERED (CDWId)
new id fields

2021-12-03 14:34 UTC, jblefkove-va commented on db/migration/V23_0__add_encounter.sql
> +    [CDWIdNumber] bigint NULL,
should these have brackets as well for consistency?

2021-12-03 14:36 UTC, taylorrassmannlibertyits commented on db/migration/V23_0__add_encounter.sql
> +    [CDWIdResourceCode] char(1) NULL,
I made them null since nothing is input yet as a precaution. I was going to do a follow on to make them `NOT NULL`. I will make the change now

2021-12-03 14:37 UTC, jblefkove-va commented on db/migration/V23_0__add_encounter.sql
> +    [CDWIdResourceCode] char(1) NULL,
Since these fields are the PK from day one, we will not have any records where they are null

2021-12-03 15:15 UTC, jblefkove-va approved these changes
:shipit:

2021-12-03 15:16 UTC, merged