added last updated to practitionerRole and updated README.
department-of-veterans-affairs/health-apis-datamart-synthetic-records pull request #395
Opened 2022-06-30 20:18 UTC by bcastillomartel-va

lastUpdated for practitionerRole resource

2022-06-30 20:21 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/MinimartMaker.java
> +     * Commit and clean up the transactions for the entity managers from the various threads.
Was this intentional? Run the formatter on the command-line and recommit

2022-06-30 20:24 UTC, bcastillomartel-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/MinimartMaker.java
> +     * Commit and clean up the transactions for the entity managers from the various threads.
I did run `mvn clean install`, let me try again

2022-07-01 13:07 UTC, taylorrassmannlibertyits commented on README.md
> +- To repopulate an existing database, retaining existing schema and records, use `./run-local.sh`
I'm confused why this shows up as a change? Just a question

2022-07-01 13:09 UTC, taylorrassmannlibertyits commented on README.md
> +- To repopulate an existing database, retaining existing schema and records, use `./run-local.sh`
Ah I see you added a `-`

2022-07-01 14:06 UTC, taylorrassmannlibertyits commented on minimart-manager/README.md
> +  - `config/lab.properties` is required with connection properties for the source database
what changed on this line?

2022-07-05 14:39 UTC, jblefkove-va requested changes
Move documentation down

2022-07-07 17:44 UTC, jblefkove-va commented on README.md
> +- To repopulate an existing database, retaining existing schema and records, use `./run-local.sh`
Now that the other documentation has moved, I don't think these bullets are necessary

2022-07-07 17:48 UTC, jblefkove-va commented on minimart-manager/README.md
> +- Whenever there are changes to the `mitre.mv.db` file, complete the following steps:
This would have more context with a link to https://github.com/department-of-veterans-affairs/health-apis-data-query/blob/master/data-query-tests/src/test/resources/mitre.mv.db

2022-07-11 14:35 UTC, jblefkove-va commented on minimart-manager/README.md
> +  - `Update docker image `./run-local.sh start`
I am going to extract these steps into their own script

2022-07-11 14:39 UTC, merged

2022-07-11 14:39 UTC, bcastillomartel-va commented on minimart-manager/README.md
> +  - `Update docker image `./run-local.sh start`
that's a major improvement, neat