Created new class to interact with ETL data and populate it into the …
department-of-veterans-affairs/health-apis-datamart-synthetic-records pull request #65
Opened 2020-09-17 14:13 UTC by that-guy-is-it

…DB, and changed populateDB class to use the new class, and also added the V_6 migration for the new table creation.

2020-09-17 14:23 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceETLStatusLoader.java
> +public class LatestResourceETLStatusLoader {
We don't capitalize acronyms, just the first letter. `LatestResourceEtlStatusLoader`

2020-09-17 14:24 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceETLStatusLoader.java
> +  public void insertIntoETLTable() {
`insertIntoEtlTable()`

2020-09-17 14:25 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceETLStatusLoader.java
> +      // Inserts value if nonexistent, updates it otherwise
This comment provides no new information. Delete it.

2020-09-17 14:27 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/PopulateDb.java
> +      // create a new ETL Loader and load the current resource data
This comment provides no new information. Delete it.

2020-09-17 14:28 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/PopulateDb.java
>        // break;
be a Boy Scout, remove this litter

2020-09-17 14:30 UTC, jblefkove-va commented on db/migration/V6_0__create_latest_resource_ETL_status.sql
> +-- This table is only used in Lab environment. It doesn't exist in prod.
For consistency with the other sql files, the description in the filename should be all lowercase

2020-09-17 14:33 UTC, jblefkove-va commented on db/migration/V6_0__create_latest_resource_ETL_status.sql
> +)WITH (DATA_COMPRESSION = PAGE)
The `DATA_COMPRESSION` setting is not relevant here and not set on any of the other tables, so let's remove it.

Although it is not required since this file is only a single statement, for consistency with the others, there should be a `GO` after 'CREATE TABLE`

2020-09-17 14:34 UTC, jblefkove-va commented on db/migration/V6_0__create_latest_resource_ETL_status.sql
> +	[ResourceName] [varchar](100) NULL,
formatting... tabs are bad

2020-09-17 14:35 UTC, jblefkove-va commented on db/migration/V6_0__create_latest_resource_ETL_status.sql
> +-- Instead, prod Datamart has a view that maps to it: App.vw_Latest_Resource_ETL_Status
These comments are superfluous. As long as `App.Latest_Resource_ETL_Status` exists in all environments, we're not really concerned with whether it's a table vs. a view.

2020-09-17 14:42 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/PopulateDb.java
> +
stray line break

2020-09-17 14:43 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceETLStatusLoader.java
> +      return;
If an exception occurs, we should allow that to propagate up, not suppress it

2020-09-17 14:50 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceETLStatusLoader.java
> +      return;
Furthermore, `e.printStackTrace()` is never acceptable.

2020-09-17 14:51 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceETLStatusLoader.java
> +    try {
This try/catch can leak resources

2020-09-17 14:58 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceETLStatusLoader.java
> +      statement.setString(2, smalldatetime);
Why not `statement.setDate(...)`?

2020-09-17 15:00 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceETLStatusLoader.java
> +      String smalldatetime = formatter.format(dateNow);
This is a little gross... these 5 lines could be achieved by using better data types.
```
 java.sql.Date now = new java.sql.Date(System.currentTimeMillis());
```

2020-09-17 15:09 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceETLStatusLoader.java
> +  final String sqlDriverClass = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
1. This isn't going to work. You can't assume that the database is always SQL Server.
2. Even if you made that bad assumption, this would be a constant: `private static final SQL_DRIVER_CLASS`

2020-09-17 15:16 UTC, bschofield-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceETLStatusLoader.java
> +  public LatestResourceETLStatusLoader(String resource) {
Remove this constructor and replace with
```
@RequiredArgsConstructor(staticName = "create")
```

2020-09-17 15:27 UTC, bschofield-va requested changes
Besides the mechanical issues in the PR, this is not going to work. It hard codes SQL server as a database and is completely ignorant that the MitreMinimartMaker supports a variety of external databases, like SQLServer, but also support in-memory H2 databases. 

You're going to need go back to the drawing board.

2020-09-18 13:22 UTC, closed without merging

2020-09-18 13:23 UTC, that-guy-is-it commented
Aborting Pull Request due to change of implementation plans.