API-1562 Updated DQ Version
department-of-veterans-affairs/health-apis-datamart-synthetic-records pull request #69
Opened 2020-09-21 21:56 UTC by that-guy-is-it

2020-09-21 22:13 UTC, jhulbert-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java
> +          LatestResourceEtlStatusEntity.class);
Alphabetical

2020-09-21 22:18 UTC, jblefkove-va requested changes
see inline

2020-09-21 22:18 UTC, jhulbert-va approved these changes

2020-09-21 22:18 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceEtlStatusLoader.java
> +                "SELECT res FROM LatestResourceEtlStatusEntity res WHERE res.resourceName = :resource")
this can be done more simply with `entityManager.find()`

2020-09-21 22:20 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java
> +      etlLoader.insertIntoEtlTable(resourceToSync, entityManager);
This should move up above this block, before the comment. This makes it erroneously appear to be part of the clean up. (Also you only need to save the entity once, so it would not go in this loop)

2020-09-22 12:47 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java
> +    etlLoader.insertIntoEtlTable(resourceToSync, LOCAL_ENTITY_MANAGER.get());
Use `getEntityManager()` instead of accessing `LOCAL_ENTITY_MANAGER` directly

2020-09-22 12:50 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java
> +          LatestResourceEtlStatusEntity.class,
While you're in here, the name `MANAGED_CLASSES`, plus the way it is used and that it is `private` and `final` suggest it was meant to be constant. So make this list `static` as well.

2020-09-22 12:51 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceEtlStatusLoader.java
> +    return entityManager.find(LatestResourceEtlStatusEntity.class, resource) != null;
Now that this method is one line, perhaps it should just be inlined instead?

2020-09-22 12:56 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceEtlStatusLoader.java
> +public class LatestResourceEtlStatusLoader {
`Loader` is pretty generic... how about `Updater` instead?

2020-09-22 12:57 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/LatestResourceEtlStatusLoader.java
> +  public void insertIntoEtlTable(String resource, EntityManager entityManager) {
`insert` implies that this is creating a new record every time

2020-09-22 13:00 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java
> +    etlLoader.insertIntoEtlTable(resourceToSync, LOCAL_ENTITY_MANAGER.get());
It doesn't really matter since these objects are created single-use and then immediately discarded, but `entityManager` makes more sense as an attribute of the class (since it wouldn't change between invocations) while resource is a parameter, i.e. `LatestResourceEtlStatusLoader.create(getEntityManager()).insertIntoEtlTable(resourceToSync)`

2020-09-22 14:12 UTC, jblefkove-va commented on minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java
> -                      // All currently existing data for LAB translates to CH
Formatter ate this comment, restore it

2020-09-22 14:22 UTC, jblefkove-va approved these changes

2020-09-22 14:22 UTC, merged