API 2883 Flyway Update
department-of-veterans-affairs/health-apis-datamart-synthetic-records pull request #74
Opened 2020-10-16 21:58 UTC by that-guy-is-it

2020-10-19 13:08 UTC, jblefkove-va submitted a review, later dismissed

2020-10-19 13:14 UTC, jhulbert-va requested changes

2020-10-19 13:14 UTC, jhulbert-va commented on build.sh
> +LOCAL_INSTALL=$(find -maxdepth 1 -name "flyway-*" | sort -V | head -1)
This is going to get any version of Flyway that exists. 
In addition, if only version 6 exists, this is going to get the same value you just set. 
I think you should find the directories and then inspect the version from there so you aren't using the same command twice in a row.

2020-10-19 13:16 UTC, jblefkove-va commented on build.sh
> +LOCAL_INSTALL=$(find -maxdepth 1 -name "flyway-*" | sort -V | head -1)
Seems okay, I wouldn't expect there to be more than one version of flyway present locally.

2020-10-19 13:19 UTC, jhulbert-va commented on build.sh
> +LOCAL_INSTALL=$(find -maxdepth 1 -name "flyway-*" | sort -V | head -1)
Regardless, I'd prefer running that command once and then inspecting the version vs getting 6 specifically, checking it exists, and then running a find again.

2020-10-19 19:09 UTC, jhulbert-va commented on build.sh
> +if [ "$LOCAL_INSTALL" != "flyway-7*" ]; then echo "WARNING: Upgrade Flyway"; fi
Opposite. This should be checking the old version. I think you want `*flyway-6*` as well.

2020-10-20 12:48 UTC, jhulbert-va commented on build.sh
> +if [[ $LOCAL_INSTALL == *flyway-6* ]]; then echo "WARNING: Upgrade Flyway"; fi
Double quotes on `LOCAL_INSTALL`

2020-10-20 13:20 UTC, bschofield-va commented on build.sh
> +if [[ $LOCAL_INSTALL == *flyway-6* ]]; then echo "WARNING: Upgrade Flyway"; fi
you might also make the warning a little more informative, i.e. what version should they upgrade to?

2020-10-20 13:22 UTC, bschofield-va commented on build.sh
> +LOCAL_INSTALL=$(find -maxdepth 1 -name "flyway-*" | sort -V | head -1)
this is incorrect, it will now detect _any_ version of Flyway, I do not want to support _any_ version

it needs to specifically look for 6 or 7

2020-10-20 13:23 UTC, bschofield-va commented on docker/Dockerfile
> +RUN wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.0.4/flyway-commandline-7.0.4-linux-x64.tar.gz | tar xz  \
Let's help out future us and make a argument for flyway version

2020-10-21 19:59 UTC, bschofield-va commented on build.sh
> +LOCAL_INSTALL=$(find -maxdepth 1 -name "flyway-[67]*" | sort -V | head -1)
@that-guy-is-it this is a simpler approach

2020-10-21 19:59 UTC, bschofield-va approved these changes

2020-10-21 20:01 UTC, jhulbert-va approved these changes
:ship:

2020-10-21 20:04 UTC, merged